name: Aggiorna file

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy_file:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout public repository
      uses: actions/checkout@v2
    - name: generate a file
      run: echo "ciao" >> file.txt

    - name: Update Repository
      run: |-
        git config user.name "autoupdate"
        git config user.email "actions@users.noreply.github.com"
        git add *
        timestamp=$(date --iso-8601=seconds)
        git commit -am "update: ${timestamp}" || exit 0
        git push
